import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

import { query, graphql } from "@/graphql";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const SettingsQuery = graphql(`
    query Settings {
      site {
        settings {
          storeName
        }
        categoryTree {
          entityId
          name
        }
      }
    }
  `);

  const { data } = await query(SettingsQuery, {});

  if (!data) {
    throw new Error(`No data in GQL response for RootLayout`);
  }

  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} container mx-auto flex min-h-screen flex-col font-sans`}
      >
        <nav className="flex items-center justify-between py-6">
          <Link className="font-bold hover:underline" href="/">
            {data.site.settings?.storeName}
          </Link>

          <ul className="flex gap-4">
            {data.site.categoryTree.map((category) => (
              <li key={category.name}>
                <Link
                  className="hover:underline"
                  href={`/categories/${category.entityId}`}
                >
                  {category.name}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        <main className="flex-1">{children}</main>

        <footer className="flex items-center justify-end pb-12 pt-16">
          <Link className="text-sm hover:underline" href="/">
            {data.site.settings?.storeName}
          </Link>
        </footer>
      </body>
    </html>
  );
}
